fix #89: err checking in last_insert_id() + test (#90)
I'll add a small change later, throwing sqlpp::postgresql::undefined_table instead of sqlpp::exception.

Error code in psql (42P01 resolves to undefined_table):

sqlpp11_tests=# \errverbose
ERROR:  42P01: relation "bla_bla_seq" does not exist
LINE 1: SELECT currval('bla_bla_seq');
                       ^
LOCATION:  RangeVarGetRelidExtended, namespace.c:426